#!/usr/bin/env python3
"""Render the detailed 4-section speaker script to a clean, formatted PDF."""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, HRFlowable, KeepTogether)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

NAVY=HexColor("#0F2A43"); ACCENT=HexColor("#C08A2B"); SLATE=HexColor("#333333"); GREY=HexColor("#6B7682")
SERIF="Times-Roman"; SERIFB="Times-Bold"; SERIFI="Times-Italic"

styles=getSampleStyleSheet()
H_TITLE=ParagraphStyle("t",fontName=SERIFB,fontSize=20,leading=24,textColor=NAVY,spaceAfter=4)
H_SUB  =ParagraphStyle("s",fontName=SERIFI,fontSize=12,leading=16,textColor=GREY,spaceAfter=2)
SEC    =ParagraphStyle("sec",fontName=SERIFB,fontSize=15,leading=19,textColor=NAVY,spaceBefore=14,spaceAfter=2)
SECMETA=ParagraphStyle("secm",fontName=SERIFI,fontSize=10.5,leading=14,textColor=ACCENT,spaceAfter=8)
CUE    =ParagraphStyle("cue",fontName=SERIFB,fontSize=11,leading=15,textColor=ACCENT,spaceBefore=8,spaceAfter=2)
BODY   =ParagraphStyle("b",fontName=SERIF,fontSize=11,leading=16,textColor=SLATE,alignment=TA_JUSTIFY,spaceAfter=5)
NOTE   =ParagraphStyle("n",fontName=SERIFI,fontSize=10,leading=14,textColor=GREY,spaceAfter=4)

sections=[
 ("SECTION 1 — Speaker 1: Introduction & Framing","Slides 1–6  ·  approx. 7–8 minutes",[
  ("Slide 1 – Title",
   "Good morning, everyone. We are [names], and our presentation is titled “Transnational Crime and the Limits of International Justice: What the Epstein Case Reveals.” We want to be clear from the outset about why we chose this case. We are not here to retell a sensational story. We are using a single, well-documented case as a lens to examine a genuinely difficult problem in international and comparative law: what happens when a crime is global in its reach, but the legal institutions built to punish it are national in their power? That mismatch — between borderless crime and bordered justice — is the thread that runs through everything we are about to say."),
  ("Slide 2 – Central Question & Roadmap",
   "Our guiding question is this: why is transnational sexual exploitation so difficult to prosecute, and what do international law and cross-border cooperation actually need in order to work? We will answer it in four parts. First, I will frame the case and show why it is international rather than purely domestic. Second, my colleague will explain the international legal framework — the treaties and the machinery of cooperation. Third, we examine how extreme wealth and mobility affect accountability. And fourth, we turn to transparency, reform, and a comparison with Japan. Two ground rules guide us throughout: we keep the focus on the victims and on the legal systems, not on lurid detail; and we limit ourselves to what courts have actually decided, rather than rumour or association."),
  ("Slide 3 – Part 1 Divider",
   "So let me begin with the framing — who Jeffrey Epstein was, and why this case refuses to stay inside any one country’s borders."),
  ("Slide 4 – Who Was Jeffrey Epstein?",
   "Jeffrey Epstein was an American financier who managed money for a small circle of the ultra-wealthy and, through that, built an extraordinary network of powerful contacts across business, politics, and academia. The criminal story begins around 2005, when police in Palm Beach, Florida opened an investigation after a parent reported the abuse of a teenage girl. That investigation produced, in 2007–08, a now-infamous non-prosecution agreement: instead of facing federal charges, Epstein pleaded to lesser state offences and registered as a sex offender. More than a decade later, in July 2019, federal prosecutors in the Southern District of New York indicted him for the sex trafficking of minors and conspiracy. He was arrested, denied bail as a flight risk, and died in custody in August 2019 — a death the New York medical examiner ruled a suicide. That death matters legally, and it is the hinge of our whole talk: because the defendant was gone, accountability could no longer run through him. It had to be pursued through other people, other institutions, and other countries."),
  ("Slide 5 – A Case That Spanned Two Decades",
   "It helps to see the chronology, because each date marks a shift in how seriously the system responded. 2008: the Florida resolution, widely criticised as far too lenient for the conduct alleged. 2019: the federal trafficking charges in New York, and Epstein’s death in custody weeks later. 2021: his close associate Ghislaine Maxwell was convicted by a federal jury of a sex-trafficking conspiracy. And 2025: a wave of document releases reopened public scrutiny and debate. Read together, the arc is striking — what began as a quiet, local plea bargain grew, over roughly two decades, into a global question about justice, wealth, and the reach of the law."),
  ("Slide 6 – Why This Is an International Story",
   "Now, why call this international rather than just an American scandal? Look at the structure of the conduct. Recruitment operated across borders, drawing in victims — including minors and foreign nationals — and moving people between locations. The money was held through offshore structures that obscured ownership. The properties spanned multiple jurisdictions: New York, Florida, a private island in the US Virgin Islands, a ranch in New Mexico, and a residence in Paris. There was even an expired passport bearing his photograph under a false name, listing Saudi Arabia as his residence — a small but vivid emblem of cross-border mobility. And the social network reached into several countries and into high public office. Here is the core tension, and please hold onto it, because the rest of our talk turns on it: the network was global, but criminal enforcement is national. To explain why that gap is so hard to close, I will hand over to our second speaker."),
 ]),
 ("SECTION 2 — Speaker 2: The International Legal Framework","Slides 7–12  ·  approx. 8–9 minutes",[
  ("Slide 7 – Part 2 Divider",
   "Thank you. My task is to set out how international law actually tries to address crime that crosses borders — and, just as importantly, to show where that law strains under pressure."),
  ("Slide 8 – What Makes a Crime “Transnational”?",
   "Let me start with a precise definition, because it matters. Under the UN framework, an offence is “transnational” if it is committed in more than one state; or committed in one state but with a substantial part of its planning, direction, or control in another; or if it has substantial effects in another state. Human trafficking is the paradigm example, because by its very nature it moves three things across borders at once: people, money, and evidence. And that is exactly where the difficulty lies. Prosecuting such a crime requires more than one country’s police, prosecutors, courts, and statutes to act in concert. Domestic criminal-justice systems were designed for domestic crime — a victim, a defendant, and a court all within one jurisdiction. When the conduct spreads across borders, those systems come under real strain. So the question we face is institutional, not merely moral: can sovereign legal systems coordinate quickly and effectively enough to keep up?"),
  ("Slide 9 – The Palermo Protocol (2000)",
   "International law’s central answer begins with the Palermo Protocol, adopted in 2000 and in force from 2003. Its full name is the UN Protocol to Prevent, Suppress and Punish Trafficking in Persons, Especially Women and Children. It gave the world its first widely agreed definition of trafficking, built on three elements: an act — such as recruitment, transport, transfer, harbouring, or receipt of a person; a means — such as threat, force, coercion, fraud, deception, or the abuse of power or of a position of vulnerability; and a purpose — exploitation, which expressly includes sexual exploitation. Crucially, where the victim is a child under eighteen, the “means” element is not required: any recruitment or harbouring of a child for exploitation is trafficking, full stop. The Protocol obliges states that join it to criminalise trafficking in their own domestic law, and with more than 190 states parties, it gives almost every country a shared legal vocabulary. That shared vocabulary is not a technicality — it is the precondition for any cooperation at all."),
  ("Slide 10 – UNTOC & Cross-Border Cooperation",
   "The Protocol does not stand alone. It supplements a parent treaty: the UN Convention against Transnational Organized Crime, known as UNTOC, also adopted in 2000. The two instruments operate together, and UNTOC supplies the practical machinery of cooperation. It provides a framework for extradition, for mutual legal assistance, and for joint investigations between states. Importantly, in many situations it can itself serve as the legal basis for cooperation even where two countries have no bilateral treaty between them — which closes a gap criminals used to exploit. It also encourages the confiscation of criminal assets and the protection of victims and witnesses. So the headline point is this: the machinery for international cooperation already exists on paper. The hard part is making it run."),
  ("Slide 11 – Jurisdiction, Extradition & MLATs",
   "Consider why running it is so hard. First, jurisdiction. A state can usually claim the power to prosecute based on its territory, or on the nationality of the offender, or sometimes of the victim. The consequence is that several states may have a concurrent right to prosecute the very same conduct — which raises hard questions about where a case should actually be brought. Second, extradition. To bring a suspect from one country to another, you generally need an extradition treaty and “dual criminality” — the act must be a crime in both states — and many countries will not extradite their own nationals at all. Third, evidence. To move testimony, records, and documents across borders lawfully, states use Mutual Legal Assistance Treaties, or MLATs. The friction is the recurring theme: these requests are slow, they can be refused on various grounds, and they tend to stall precisely when a suspect has the resources and connections to contest every step. So the tools exist — but speed, resources, and political will decide whether they actually work."),
  ("Slide 12 – Foreign Nationals & Quasi-Diplomatic Figures",
   "This case illustrates those frictions through its people. Ghislaine Maxwell, a British national, was convicted by a New York federal jury in December 2021 of a sex-trafficking conspiracy, and was sentenced in 2022 to twenty years in prison. Separately, Prince Andrew settled a US civil claim brought by Virginia Giuffre in 2022 — a settlement with no admission of liability — and subsequently stepped back from his military titles and royal style. From these we can draw two careful lessons. First, high status confers no criminal immunity; but it can create real practical and diplomatic hurdles to investigation and trial. Second, foreign nationality genuinely complicates arrest, extradition, and the gathering of evidence abroad. And let me underline the discipline we hold ourselves to: we speak only of what has been adjudicated — a conviction, a sentence, a settled civil claim — and not of speculation or guilt by association. With the framework now in place, our third speaker takes up wealth and mobility."),
 ]),
 ("SECTION 3 — Speaker 3: Wealth, Mobility & Impunity","Slides 13–16  ·  approx. 7 minutes",[
  ("Slide 13 – Part 3 Divider",
   "Thanks. I want to examine how resources — wealth and mobility — can delay accountability, though, as we will see, not always defeat it."),
  ("Slide 14 – Offshore Wealth & Global Mobility",
   "Consider the mechanics of how money becomes a shield. Offshore companies and trusts in secrecy-friendly jurisdictions can obscure who truly owns an asset, which slows any investigation that tries to follow the money. Owning property in several jurisdictions provides not just places to live, but places to store value and to move between. Private travel reduces the friction and the scrutiny that ordinary border crossings impose. And multiple identity documents — including the false-name passport we mentioned earlier — illustrate a concrete capacity to evade. Put these together and you see a pattern: wealth is converted into mobility, and mobility is converted into delay. I want to stress that this pattern is not unique to one individual. It is, broadly, how illicit elite wealth tends to behave anywhere in the world, which is exactly why it is a problem for legal systems and not just a biographical detail."),
  ("Slide 15 – “Elite Impunity”: 2008 vs 2019",
   "The clearest way to see the effect is to compare two moments a decade apart. In 2008, in Florida, the matter was resolved by a non-prosecution agreement: the federal investigation was effectively halted, Epstein pleaded to lesser state offences, and he served roughly thirteen months in county jail under an arrangement that allowed extensive work release. The agreement also limited exposure for others, and the victims were not properly consulted — a federal judge later found that this failure to confer with them violated their rights under US victims’-rights law. Now contrast 2019, when federal prosecutors in New York charged him with sex-trafficking conspiracy and a court ordered him held without bail, treating the matter as serious organised wrongdoing. Same underlying conduct; two profoundly different responses. That contrast is what people mean by “elite impunity” — not that the law never catches up, but that wealth can purchase a softer outcome and, above all, a great deal of time."),
  ("Slide 16 – Would Other Systems Have Acted Differently?",
   "That naturally raises a comparative-law question: would a different legal system have handled this differently? Several contrasts are worth weighing. There is the adversarial model, as in the US and UK, versus the inquisitorial model, where an investigating magistrate — France’s juge d’instruction, for example — can drive an investigation independently of the prosecutor. There is the role of victims, who in some civil-law systems can join the proceedings as a civil party much earlier and more formally. There are limitation periods, which differ sharply — some countries have abolished or extended them for child sexual offences. And there is plea bargaining, which is central to American practice but far more limited elsewhere, changing the incentive to settle a case quietly. So the question I will leave with the room is genuinely open: would the UK, France, or Japan have moved faster — or slower? Our final speaker now turns to accountability and the lessons."),
 ]),
 ("SECTION 4 — Speaker 4: Accountability, Transparency & Conclusion","Slides 17–20  ·  approx. 8 minutes",[
  ("Slide 17 – Part 4 Divider",
   "Thank you. I will close on accountability — and specifically on how we might design cross-border justice so that it genuinely protects victims rather than exposing them."),
  ("Slide 18 – The 2025 Document-Release Wave",
   "In 2025, a wave of disclosures driven by transparency measures in the United States released a large volume of case-related documents. The impulse behind this was legitimate: a real public demand for accountability and openness about how the case had been handled. But survivors raised a serious and specific concern — that the way the disclosures were done made it easy to identify the people who had been abused, while doing far less to clarify those who may have been involved in the abuse. That captures a genuine tension at the heart of transparency policy: the public interest in openness can collide with the privacy and the physical safety of victims. The lesson we draw is that transparency is not automatically just. Its design — what you release, what you redact, and whom you protect by default — determines who it actually serves."),
  ("Slide 19 – Reform Proposals & a Japan Comparison",
   "So what would a better system look like? We propose four practical reforms. First, faster and better-resourced channels for mutual legal assistance and extradition, so cooperation does not die of delay. Second, victim-centred disclosure rules that shield victims’ identities by default, so transparency does not become re-victimisation. Third, stronger cross-border tracing and recovery of criminal assets, so wealth cannot simply be hidden abroad. And fourth, greater harmonisation of definitions, so cooperation is not blocked merely because two countries’ laws do not match. For our audience here, the comparison with Japan is instructive. Japan operates a national framework against trafficking and is assessed every year in the US State Department’s Trafficking in Persons report, which ranks countries by tier — a useful external benchmark for how a non-Western system measures up on cross-border cooperation. The encouraging conclusion is that better justice across borders is, for the most part, an engineering and resourcing problem, not a gap in legal principle."),
  ("Slide 20 – Conclusion: Four Takeaways",
   "Let me pull the whole presentation together with four takeaways. First, crime crosses borders, but justice often does not — networks are global while enforcement remains national. Second, the legal tools already exist — the Palermo Protocol and UNTOC supply the framework, and the real gap is coordination, not law. Third, wealth buys time, not immunity — here, mobility delayed accountability for years but did not, in the end, wholly prevent it. And fourth, transparency must be designed to protect victims — disclosure should expose enablers, not endanger survivors. Our sources are listed on the slide, including the Palermo Protocol, UNTOC, the US court filings in the Epstein and Maxwell cases, and the State Department’s reports. Thank you very much — we would be glad to take your questions."),
 ]),
]

doc=SimpleDocTemplate("/home/user/Koki/Speaker_Script_4_Sections.pdf",pagesize=A4,
    topMargin=18*mm,bottomMargin=16*mm,leftMargin=20*mm,rightMargin=20*mm,
    title="Epstein Presentation — Speaker Script (4 sections, detailed)")
fl=[]
fl.append(Paragraph("Transnational Crime &amp; the Limits of International Justice",H_TITLE))
fl.append(Paragraph("What the Epstein Case Reveals — Detailed Speaker Script (4 sections, ~30 min)",H_SUB))
fl.append(Spacer(1,3))
fl.append(HRFlowable(width="100%",thickness=2,color=ACCENT,spaceAfter=6))
fl.append(Paragraph("Note: this topic involves the sexual abuse of minors. Keep the focus on victims and on how legal systems respond, and limit claims to what courts have adjudicated. Brackets like [names] are placeholders to fill in.",NOTE))

for title,meta,cues in sections:
    block=[HRFlowable(width="100%",thickness=0.6,color=GREY,spaceBefore=8,spaceAfter=6),
           Paragraph(title,SEC),Paragraph(meta,SECMETA)]
    fl.append(KeepTogether(block))
    for cue,body in cues:
        fl.append(KeepTogether([Paragraph("["+cue+"]",CUE)]))
        fl.append(Paragraph(body,BODY))

doc.build(fl)
print("wrote Speaker_Script_4_Sections.pdf")
